SuperElf/UI_SuperElf/Controllers/ClubController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Logic_Factories_SuperElf;
using Logic_Interfaces_SuperElf;
using Microsoft.EntityFrameworkCore;
using UI_SuperElf.Models;

namespace UI_SuperElf.Controllers
{
    public class ClubController : Controller
    {
        private readonly ICompetition _competition = Competition_Factory.CreateCompetition();
        private readonly ICompetitionContainer _competitionContainer =
            CompetitionContainer_Factory.CreateCompetitionContainer();
        // GET: ClubController
        public ActionResult Index()
        {
            try
            {
                ClubPipeline clubPipeline = new ClubPipeline();
                List<IClub> clubs = _competition.GetAllClubs();
                foreach (IClub club in clubs)
                {
                    ClubViewModel clubViewModel = new ClubViewModel();
                    clubViewModel.clubId = club.clubId;
                    clubViewModel.clubName = club.clubName;
                    clubViewModel.competitionId = club.competitionId;
                    clubPipeline.Clubs.Add(clubViewModel);
                }

                clubPipeline.Competitions = _competitionContainer.GetAllCompetitions();
                return View(clubPipeline);
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // GET: ClubController/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                return ClubCreateViewModelById(id);
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // GET: ClubController/Create
        public ActionResult Create()
        {
            try
            {
                ClubCreateViewModel club = new ClubCreateViewModel();
                club.allCompetitions = _competitionContainer.GetAllCompetitions();
                return View(club);
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // POST: ClubController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ClubViewModel newClub)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ClubCreateViewModel club = new ClubCreateViewModel();
                    club.allCompetitions = _competitionContainer.GetAllCompetitions();
                    return View(club);
                }

                _competition.AddClub(newClub.clubId, newClub.competitionId, newClub.clubName);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // GET: ClubController/EditName/5
        public ActionResult EditName(int id)
        {
            try
            {
                return ClubCreateViewModelById(id);
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // POST: ClubController/EditName/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditName(int clubId, ClubCreateViewModel updatedClub)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return ReturnToClub(clubId);
                }

                IClub club = _competition.GetClubById(clubId);
                string newClubName = updatedClub.clubName;
                club.UpdateClubName(club, newClubName);
                return RedirectToAction("Details", new {id = clubId});
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // GET: ClubController/EditCompetition/5
        public ActionResult EditCompetition(int id)
        {
            try
            {
                return ClubCreateViewModelById(id);
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // POST: ClubController/EditCompetition/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCompetition(int clubId, ClubCreateViewModel updatedClub)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return ReturnToClub(clubId);
                }

                IClub club = _competition.GetClubById(clubId);
                int newCompetition = updatedClub.competitionId;
                club.UpdateCompetition(club, newCompetition);
                return RedirectToAction("Details", new {id = clubId});
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }
        // GET: ClubController/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                return ClubCreateViewModelById(id);
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // POST: ClubController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, ClubCreateViewModel club)
        {
            try
            {
                if (id == 0)
                {
                    ModelState.AddModelError("", "Delete could not be processed, try again later.");
                    return RedirectToAction("Index");
                }

                _competition.DeleteClub(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }
        // Create clubCreateViewModel by id
        private ActionResult ClubCreateViewModelById(int id)
        {
            IClub clubById = _competition.GetClubById(id);
            ClubCreateViewModel club = new ClubCreateViewModel();
            club.clubId = clubById.clubId;
            club.competitionId = clubById.competitionId;
            club.clubName = clubById.clubName;
            club.allCompetitions = _competitionContainer.GetAllCompetitions();
            return View(club);
        }
        // Return correct club to view when an error occurs
        private ActionResult ReturnToClub(int playerId)
        {
            ModelState.AddModelError("", "Update could not be processed, try again later.");
            return ClubCreateViewModelById(playerId);
        }
    }
}

SuperElf/UI_SuperElf/Controllers/TeamController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Logic_Factories_SuperElf;
using Logic_Interfaces_SuperElf;
using SharedFiles;
using UI_SuperElf.Models;

namespace UI_SuperElf.Controllers
{
    public class TeamController : Controller
    {
        private readonly ITeam _team = Team_Factory.CreateTeam();
        private readonly IUser _user = User_Factory.CreateUser();
        private readonly IClub _club = Club_Factory.CreateClub();
        private readonly IUserContainer _userContainer = UserContainer_Factory.CreateUserContainer();
        // GET: TeamController
        public ActionResult Index()
        {
            return View();
        }

        // GET: TeamController/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                TeamViewModel team = new TeamViewModel();
                ITeam teamDetails = _user.GetTeamDetailsById(id);
                List<IPlayer> players = _user.GetPlayersFromTeam(id);
                List<IPlayer> sortedPlayers = players.OrderBy(x => x.position).ToList();
                if (players.Count != 0)
                {
                    foreach (IPlayer player in sortedPlayers)
                    {
                        team.players.Add(player);
                    }
                }

                team.formations = _team.GetAllFormations();
                team.formation = teamDetails.formationId;
                team.teamPoints = teamDetails.teamPoint;
                return View(team);
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        public ActionResult MyTeam(int id)
        {
            try
            {
                MyTeamViewModel myTeam = new MyTeamViewModel();
                ITeam teamDetails = _user.GetTeamDetailsById(id);
                List<IPlayer> players = _user.GetPlayersFromTeam(id);
                List<IPlayer> sortedPlayers = players.OrderBy(x => x.position).ToList();
                if (players.Count != 0)
                {
                    foreach (IPlayer player in sortedPlayers)
                    {
                        myTeam.Players.Add(player);
                    }
                }

                myTeam.formations = _team.GetAllFormations();
                myTeam.formation = teamDetails.formationId;
                myTeam.teamPoints = teamDetails.teamPoint;
                return View(myTeam);
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // Get formation for create team
        public ActionResult ChooseTeamFormation()
        {
            try
            {
                MyTeamViewModel myTeamViewModel = new MyTeamViewModel();
                myTeamViewModel.formations = _team.GetAllFormations();
                return View(myTeamViewModel);
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // GET: TeamController/Create
        public ActionResult Create(int id)
        {
            try
            {
                TeamCreateViewModel teamCreateViewModel = new TeamCreateViewModel();
                teamCreateViewModel.keepers = _club.GetAllKeepers();
                teamCreateViewModel.defenders = _club.GetAllDefenders();
                teamCreateViewModel.midfielders = _club.GetAllMidfielders();
                teamCreateViewModel.forwards = _club.GetAllForwards();
                teamCreateViewModel.formationId = id;
                return View(teamCreateViewModel);
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }

        // POST: TeamController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TeamAddModel newTeam)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    TeamCreateViewModel teamCreateViewModel = ReturnTeamCreateViewModel(newTeam);
                    ModelState.AddModelError("", "Select for each position a player.");
                    return View(teamCreateViewModel);
                }

                List<int> players = AddPlayerIdsToList(newTeam);
                if (players.Distinct().Count() != 11)
                {
                    TeamCreateViewModel teamCreateViewModel = ReturnTeamCreateViewModel(newTeam);
                    ModelState.AddModelError("", "Select 11 different players for your team.");
                    return View(teamCreateViewModel);
                }

                List<int> clubs = AddClubIdsToList(players);
                if (clubs.Distinct().Count() != 11)
                {
                    TeamCreateViewModel teamCreateViewModel = ReturnTeamCreateViewModel(newTeam);
                    ModelState.AddModelError("", "Select players from 11 different clubs for your team.");
                    return View(teamCreateViewModel);
                }

                int teamId = _user.AddTeam(newTeam.userId, newTeam.formationId);
                if (teamId == 0)
                {
                    TeamCreateViewModel teamCreateViewModel = ReturnTeamCreateViewModel(newTeam);
                    ModelState.AddModelError("", "You already have a team or the database could not connect.");
                    return View(teamCreateViewModel);
                }

                _user.AddPlayersToTeam(teamId, players);
                return RedirectToAction("MyTeam", new {id = newTeam.userId});
            }
            catch
            {
                return RedirectToAction("Error", "Home");
            }
        }
        
        // GET: TeamController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: TeamController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TeamController/Delete/5
        public ActionResult Delete(int id)
        {
            
            return View();
        }

        // POST: TeamController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            // Delete player_team then delete team
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        // Add playerIds from selected players to list
        private List<int> AddPlayerIdsToList(TeamAddModel newTeam)
        {
            List<int> players = new List<int>();
            players.Add(newTeam.playerId1);
            players.Add(newTeam.playerId2);
            players.Add(newTeam.playerId3);
            players.Add(newTeam.playerId4);
            players.Add(newTeam.playerId5);
            players.Add(newTeam.playerId6);
            players.Add(newTeam.playerId7);
            players.Add(newTeam.playerId8);
            players.Add(newTeam.playerId9);
            players.Add(newTeam.playerId10);
            players.Add(newTeam.playerId11);
            return players;
        }
        // Add clubIds from selected players to list
        private List<int> AddClubIdsToList(List<int> players)
        {
            List<int> clubs = new List<int>();
            List<IPlayer> allPlayers = _club.GetAllPlayers();
            foreach (int playerId in players)
            {
                foreach (IPlayer player in allPlayers)
                {
                    if (player.playerId == playerId)
                    {
                        clubs.Add(player.club);
                    }
                }
            }
            return clubs;
        }
        // Return teamCreateViewModel to give error in teamselection
        private TeamCreateViewModel ReturnTeamCreateViewModel(TeamAddModel newTeam)
        {
            TeamCreateViewModel teamCreateViewModel = new TeamCreateViewModel();
            teamCreateViewModel.keepers = _club.GetAllKeepers();
            teamCreateViewModel.defenders = _club.GetAllDefenders();
            teamCreateViewModel.midfielders = _club.GetAllMidfielders();
            teamCreateViewModel.forwards = _club.GetAllForwards();
            teamCreateViewModel.formationId = newTeam.formationId;
            return teamCreateViewModel;
        }
    }
}

SuperElf/UI_SuperElf/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuperElf</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
@if (Context.Session.GetString("_SessionBlackMode") == "True")
{
    <body style="background-color: rgb(31,31,35); color: rgb(239,239,241)">
        <header>
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark box-shadow mb-3" style="background-color: rgb(0,142,68)">
                    <div class="container">
                        <a class="navbar-brand" style="color: white"><image src=""></image>SuperElf</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                            <ul class="navbar-nav flex-grow-1">
                                @if (Context.Session.GetString("_SessionName") != null)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Player" asp-action="Index">Players</a>
                                    </li>
                                    @*<li class="nav-item">
                                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Poules</a>
                                        </li>*@
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Team" asp-action="MyTeam" asp-route-id="@Context.Session.GetInt32("_SessionUserId")">My team</a>
                                    </li>
                                    @if ((Context.Session.GetString("_SessionIsAdmin") == "True") || ((Context.Session.GetString("_SessionIsMod") == "True")))
                                    {
                                        @*<li class="nav-item">
                                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Teams</a>
                                            </li>*@
                                        <li class="nav-item">
                                            <a class="nav-link text-light" asp-area="" asp-controller="Formation" asp-action="Index">Formations</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-light" asp-area="" asp-controller="Club" asp-action="Index">Clubs</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-light" asp-area="" asp-controller="Competition" asp-action="Index">Competitions</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-light" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                                        </li>
                                    }
                                }
                            </ul>
                        </div>

                        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                            <ul class="navbar-nav ml-auto">
                                @if (Context.Session.GetString("_SessionName") == null)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Login" asp-action="Login">Login</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                                    </li>
                                }
                                @if (Context.Session.GetString("_SessionName") != null)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="User" asp-action="MyProfile" asp-route-id="@Context.Session.GetInt32("_SessionUserId")">My Profile</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light">Welcome @Context.Session.GetString("_SessionName") </a>
                                    </li>
                                }
                            </ul>
                        </div>

                    </div>
                </nav>
            </header>
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>


            <script src="~/lib/jquery/dist/jquery.min.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            @RenderSection("Scripts", required: false)
    </body>
}
else
{
<body>
        <header>
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3" style="background-color: rgb(0,142,68)">
                    <div class="container">
                        <a class="navbar-brand" style="color: white"><image src=""></image>SuperElf</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                            <ul class="navbar-nav flex-grow-1">
                                @if (Context.Session.GetString("_SessionName") != null)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Player" asp-action="Index">Players</a>
                                    </li>
                                    @*<li class="nav-item">
                                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Poules</a>
                                        </li>*@
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Team" asp-action="MyTeam" asp-route-id="@Context.Session.GetInt32("_SessionUserId")">My team</a>
                                    </li>
                                    @if ((Context.Session.GetString("_SessionIsAdmin") == "True") || ((Context.Session.GetString("_SessionIsMod") == "True")))
                                    {
                                        @*<li class="nav-item">
                                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Teams</a>
                                            </li>*@
                                        <li class="nav-item">
                                            <a class="nav-link text-light" asp-area="" asp-controller="Formation" asp-action="Index">Formations</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-light" asp-area="" asp-controller="Club" asp-action="Index">Clubs</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-light" asp-area="" asp-controller="Competition" asp-action="Index">Competitions</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-light" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                                        </li>
                                    }
                                }
                            </ul>
                        </div>

                        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                            <ul class="navbar-nav ml-auto">
                                @if (Context.Session.GetString("_SessionName") == null)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Login" asp-action="Login">Login</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                                    </li>
                                }
                                @if (Context.Session.GetString("_SessionName") != null)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="User" asp-action="MyProfile" asp-route-id="@Context.Session.GetInt32("_SessionUserId")">My Profile</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-light">Welcome @Context.Session.GetString("_SessionName") </a>
                                    </li>
                                }
                            </ul>
                        </div>

                    </div>
                </nav>
            </header>
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>


            <script src="~/lib/jquery/dist/jquery.min.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            @RenderSection("Scripts", required: false)
    </body>
}
    
</html>